//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     el código se vuelve a generar. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clase2609
{
    public partial class Contact
    {
    }
}
